server:
  port: 8060

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: employee-service
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/v1/employees/**

            - id: department-service
              uri: lb://DEPARTMENT-SERVICE
              predicates:
                - Path=/api/v1/departments/**

          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins:
                  - http://localhost:3000
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                allowedHeaders:
                  - "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
