server:
  port: 8060

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: employee-service
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/v1/employees/**

            - id: department-service
              uri: lb://DEPARTMENT-SERVICE
              predicates:
                - Path=/api/v1/departments/**

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**

          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins:
                  - http://localhost:3000
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"

eureka:
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
