server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/umeshbile/employee-management-config.git
          default-label: main
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
