server:
  port: 8082

spring:
  application:
    name: department-service

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/department_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Umibs@22
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.ems.employee: DEBUG

jwt:
  secret: 12345678901234567890123456789012abcdefgh
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
    healthcheck:
      enabled: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
