server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Umibs@22
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.ems.employee: DEBUG
jwt:
  secret: 12345678901234567890123456789012abcdefgh
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true

    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}

resilience4j:

  circuitbreaker:

    instances:

      departmentService:

        slidingWindowType: COUNT_BASED

        slidingWindowSize: 10

        minimumNumberOfCalls: 5

        failureRateThreshold: 50

        waitDurationInOpenState: 10s

        permittedNumberOfCallsInHalfOpenState: 3

        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      departmentService:
        maxAttempts: 3

        waitDuration: 1s

        enableExponentialBackoff: true

        exponentialBackoffMultiplier: 2

  bulkhead:

    instances:

      departmentService:

        maxConcurrentCalls: 20

        maxWaitDuration: 500ms


