server:
  port: 8084
  
spring:

  kafka:

    bootstrap-servers: host.docker.internal:9092

    consumer:

      group-id: notification-service

      auto-offset-reset: earliest

      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer

      properties:

        spring.json.trusted.packages: "com.ems.*"

eureka:
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/
